config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  namespace :admin do
    resources :orders do
      member do
        patch :mark_paid
      end
    end
    resources :avatars do
      member do
        get :crop
      end
    end
  end

  ActiveAdmin.routes(self)
  get '/jobs/abroad', to: 'offers#abroad'
  get '/jobs/poland', to: 'offers#poland'
  get '/jobs/outdated_offer', to: 'offers#no_offer_found'
  get '/premium', to: 'products#index'
  get '/subscribe', to: 'newsletter_subscriptions#new', as: :new_newsletter_subscription
  resource :newsletter_subscription, only: %i[create destroy], path: '/subscribe'
  get '/unsubscribe', to: 'newsletter_subscriptions#unsubscribe'
  get '/regulamin', to: 'pages#tos'
  get '/regulamin/zalacznik1', to: 'pages#appendix1'
  get '/rodo', to: 'pages#rodo'
  get '/contact', to: 'pages#contact'
  get '/platnosci', to: 'pages#dotpay_payments', as: :payments

  resources :offers, path: '/jobs', except: :index do
    member do
      patch :publish
      patch :unpublish
      get :promote
      patch :promote, to: 'offers#add_premium'
    end

    collection do
      patch :batch_action
    end
    resources :applications, only: :create
  end
  post '/jobs/favourite/:offer_id', to: 'offer_saves#create', as: :offer_save
  post '/jobs/send_emai/:offer_id', to: 'offer_saves#email', as: :offer_email
  delete '/unfavourite_offer', to: 'offer_saves#destroy', as: :destroy_offer_save

  resource :cart, only: %i[show destroy], controller: 'cart' do
    patch :finalize
  end
  resources :cart_items, only: %i[create edit update destroy]

  get '/orders/place', to: 'orders#place', as: :place_order

  resources :orders, only: %i[index create show destroy] do
    get :payment
    get :thank_you
  end

  get '/offers/:offer_id/apply', to: 'applications#new', as: :new_offer_application
  get '/my_offers', to: 'offers#my_offers'

  resources :resumes
  get 'candidate/edit_skills', to: 'candidates#edit_skills'
  get 'candidate/edit_profile', to: 'candidates#edit', as: :edit_candidate_profile
  resource :profile, only: :show
  resource :dashboard, only: :show
  resources :education_items, except: %i[new edit]
  resources :work_items, except: %i[new edit]

  get '/imported_offers/select_company' => 'imported_offers#select_company'
  post '/imported_offers/publish' => 'imported_offers#publish'

  scope '/api' do
    get 'skills/(:term)' => 'autocomplete#skills', as: :autocomplete_skills
    get 'professions/(:term)' => 'autocomplete#professions', as: :autocomplete_professions
    get 'schools/(:term)' => 'autocomplete#schools', as: :autocomplete_schools
    get 'organizations/(:term)' => 'autocomplete#organizations', as: :autocomplete_organizations
    get 'provinces/(:country_id)/(:element_id)' => 'provinces#index', as: :provinces
    scope '/dotpay' do
      post 'confirm_payment' => 'dotpay#confirm'
    end
    scope '/jooble' do
      get 'jobs_feed.xml', to: 'feed#jooble'
    end
    scope '/jobsora' do
      get 'jobs_feed.xml', to: 'feed#jooble'
    end
    scope '/adzuna' do
      get 'jobs_feed.xml', to: 'feed#adzuna'
    end
    scope '/trovit' do
      get 'trovit_feed.xml', to: 'feed#trovit'
    end
    post '/confirm_lfw', to: 'candidates#confirm_lfw'
    scope '/hrlink' do
      get 'import', to: 'import#hrlink'
      get 'region_list', to: 'feed#region_list'
    end
  end

  devise_scope :candidate do
    get '/sign_up', to: 'candidates/registrations#new'
  end

  devise_for :candidates, controllers: {
    omniauth_callbacks: 'candidates/omniauth_callbacks',
    registrations: 'candidates/registrations', sessions: 'sessions'
  }
  devise_for :companies, controllers: { registrations: 'companies/registrations', sessions: 'sessions' }
  devise_for :users, controllers: { sessions: 'sessions' }, skip: :registrations, path: ''
  resources :candidates do
    get :mailing_list, on: :collection
    resources :favourite_offers, only: [:index]
  end
  get 'favourite_offer/(:candidate_id)/(:offer_id)', to: 'favourite_offers#create', as: 'add_offer_to_favourites'

  resources :companies, only: %i[show index update edit] do
    get :mailing_list, on: :collection
    resources :offers, only: [:index], controller: 'company_offers'
    resources :blog_posts, only: %i[show index create new], path: '/blog'
    member do
      post :vote
    end
  end
  resources :blog_posts, path: '/blog', only: %i[show destroy edit update]
  resources :skill_items, path: 'skills', only: %i[create destroy]
  resources :cv_items, path: 'cv_items', only: %i[create destroy]
  get '/edit_avatar', to: 'avatars#new'
  get '/crop_avatar', to: 'avatars#crop'
  resource :avatar, only: %i[create update]
  root to: 'home#home'
  get '*path', to: 'application#error404'
end

app/models/company.rb
# frozen_string_literal: true

class Company < User
  devise :registerable
  has_many :offers, dependent: :destroy
  has_many :applications, through: :offers
  has_many :subscriptions
  has_many :blog_posts, foreign_key: :user_id
  belongs_to :location, optional: true
  validates :name, uniqueness: true, presence: true

  def self.published_offers
    offers.where('published_at IS NOT NULL')
  end

  accepts_nested_attributes_for :location

  extend FriendlyId
  friendly_id :name, use: %i[slugged finders]

  scope :premium_users, -> { where('premium_until > NOW()') }
  scope :featured, -> { premium_users.order('users.updated_at DESC') }

  def self.search(query)
    where('name ILIKE ?', '%' + sanitize_sql_like(query) + '%')
  end

  def premium?
    premium_until && premium_until > Time.now
  end

  def display_name
    name
  end

  def sex; end

  # balance is the amount of money given to a Company so they can buy premium services
  # when placing an order, Company's balance is reduced, and the same amount is deducted
  # from the order's total to calculate amount due.
  def reduce_balance(total)
    return if balance.nil? || balance.zero?
    discount = Prices.discount(total.to_d, balance)
    update(balance: balance - discount)
    discount
  end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    redirect_to(root_path, alert: I18n.t('devise.failure.already_authenticated')) && return if logged_in?
    @heading = I18n.t('registrations.company_heading')
    super
  end

  # POST /resource
  # def create
  # super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :find_user, only: %i[show edit update]
  helper_method :company

  before_action :set_province_list, only: :edit
  before_action :set_country_list, only: :edit

  authorize_resource

  def index
    @companies = Company.includes(:avatar).page(params[:page])
    @companies = if params[:q].present?
                   @companies.order('LOWER(name)').search(params[:q])
                 else
                   @companies.order('premium_until DESC NULLS LAST, published_offers_count DESC, updated_at DESC')
                 end
    respond_to do |f|
      f.html
      f.js
      f.xlsx do
        @companies = Company.order('LOWER(name)')
        render xlsx: 'index', filename: Time.zone.now.strftime('%Y%m%d_pracodawcy.xlsx')
      end
    end
  end

  def mailing_list
    @collection = if params['ids'].nil?
                    Company.order('LOWER(name)')
                  else
                    Company.where('id in (?)', params['ids'].split(','))
                  end
    respond_to do |f|
      f.xlsx do
        response.headers['Content-Disposition'] = "attachment; filename=
          #{Time.zone.now.strftime('%Y_%m_%d_mailing_pracodawcy.xlsx')}"
      end
    end
  end

  def edit
    if company_signed_in?
      @company = current_company
      @company.build_location
    else
      redirect_to root_path
    end
  end

  def show
    redirect_to company, status: :moved_permanently if request.path != company_path(company)
    @blog_posts = company.blog_posts.ordered
  end

  def update
    company = current_company
    if company.update(company_params)
      redirect_to company
    else
      respond_to do |f|
        f.html do
          flash.alert = 'The profile could not be saved.'
        end
        f.js { render_js_errors_for company }
      end
    end
  end

  private

  def company
    @company ||= find_user
  end

  def find_user
    if params[:id].present?
      @company = User.find(params[:id])
    elsif company_signed_in?
      @company = current_user
    end
  end

  def company_params
    params.require(:company).permit(:name, :website, :description, location_attributes: %i[country_id province_id city])
  end

  def set_province_list
    @provinces = if @company.location.try(:country).present?
                   @company.location.country.provinces.local_order
                 else
                   Province.where(country_id: Country::POLAND_ID).local_order
                 end
  end

  def set_country_list
    @countries = Country.local_order
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
  def prepare_company_meta_description(company)
    description = ActionView::Base.full_sanitizer.sanitize(company.description) if company.description.present?
    description = t('companies.show.meta_description', company: company.name) if description.nil?
    description
  end
end

app/views/companies/_company.html.haml
- if defined?(tile) && tile
  = link_to company do
    .company.company-row.company-row--tile{id: dom_id(company)}
      .company-row__left
        = avatar_for company, size: 'thumb'
      - if company.name.present? && company.name.length > 32
        - containerClasses = 'company-row__center company-row__center--no-margin-top'
      - else
        - containerClasses = 'company-row__center'
      %div{class: containerClasses}
        - if company.name.present? && company.name.length > 25
          - classNames = 'company-row__name company-row__name--long'
        - else
          - classNames = 'company-row__name'
        - name = company.name
        - name = highlight_substring(name, params[:q]) if params[:q].present?
        %span{class: classNames}= name
        %br/
        %small
          = t('plurals.offer', count: company.published_offers_count || 0)

-else
  .card.company__header#company_info
    .company__avatar
      = avatar_for company, size: :thumb, editable: can?(:edit, company)

    .company__name_container
      %h2.company__name.company__name--margin-top
        - unless request.path == company_path(company)
          = link_to company.name, company
        - else
          = company.name
    .company__header__offer_count.hide-for-small-only
      %h1= (count = company.offers.published.count)
      = t('companies.show.active_job_offers', count: count)

  .row.container.show-for-small-only
    .company__header__offer_count
      %h1= count
      = t('companies.show.active_job_offers', count: count)

app/views/companies/_info_card.html.haml
.card.company__header#company_info
  .company__avatar
    = avatar_for company, size: :thumb, editable: can?(:edit, company)

  .company__name_container
    %h2.company__name.company__name--margin-top
      - unless request.path == company_path(company)
        = link_to company.name, company
      - else
        = company.name
  .company__header__offer_count.hide-for-small-only
    %h1= (count = company.offers.published.count)
    = t('companies.show.active_job_offers', count: count)

.row.container.show-for-small-only
  .company__header__offer_count
    %h1= count
    = t('companies.show.active_job_offers', count: count)

app/views/companies/_menu.html.haml
.tabs
  - {t('.description') => company_path(company), t('.blog') => company_blog_posts_path(company_id: company), t('.offers') => company_offers_path(company_id: company)}.each do |name, path|
    - if current_page?(path)
      %li.tabs__tab.tabs__tab--active= link_to name, path
    - else
      %li.tabs__tab= link_to name, path


  - if can? :edit, company
    %li.tabs__tab.blue-bg= link_to fa_icon('pencil', text: t('actions.edit')), edit_company_path(company)

app/views/companies/_search.html.haml
%section.company_search.large-8.large-offset-2.medium-10.medium-offset-1.columns
  = form_for companies_path, method: :get, remote: true do |f|
    .row
      .input-group
        = f.text_field :q, name: 'q', id: "company_search_q", placeholder: t('.placeholder'), class: 'input-group-field', autocomplete: 'off', autofocus: !mobile?
        .input-group-button
          = f.button t('.submit'), class: 'button primary expanded search_bar__right'

:javascript
  var previousVal, formTimeout;
  document.getElementById('company_search_q').addEventListener('input', e => {
    let currentVal = e.target.value;
    if (currentVal == previousVal) return;
    previousVal = currentVal;
    clearTimeout(formTimeout);
    formTimeout = setTimeout(function() {
      if (!currentVal) {
        document.getElementById('companies').innerHTML = '';
        document.getElementById('pagination').innerHTML = '';
      }
      $(this).trigger('submit.rails');
    }.bind(e.target.form), 400);
  });

app/views/companies/edit.html.haml
%h1= t('.heading')

= simple_form_for company, remote: true, authenticity_token: true do |f|
  = error_messages_for company
  = f.input :name, input_html: { size: 35, class: 'auto-width' }
  .row
    .columns.medium-4
      = f.input :website
    .columns.medium-4
      = f.input :phone
    .columns.medium-4
      = f.input :contact_email
    = f.simple_fields_for :location do |ff|
      = render 'location_fields', f: ff, single: true

  = render 'pagedown', f: f
  = f.submit "Submit", class: 'button expanded success'

app/views/companies/index.html.haml
- set_meta_tags title: t('.heading').titleize,
                description: t('.meta_description')


- breadcrumb :companies
- content_for :banner do
  .row
    %h2.text-center= t('.heading')
    .row= render 'search'

.three-column-grid#companies= render @companies, tile: true
#pagination= paginate @companies

app/views/companies/index.js.haml
:plain
- if @companies.first_page? && params[:q].present?
  $('#companies').html('#{j render @companies, tile: true}');
- else
  $('#companies').append('#{j render @companies, tile: true}');
- pagination = @companies.last_page? ? '' : j(paginate @companies)
document.getElementById('pagination').innerHTML = '#{pagination}';

app/views/companies/show.haml
- set_meta_tags title: [t('offers.show.company'), @company.name, @company.location].join(' '),
                description: prepare_company_meta_description(@company)

- breadcrumb :company, company
.row
  = render company
  - if can? :edit, company
    .show-for-small-only
      = link_to t('offers.add_new_offer'), new_offer_path, class: 'button expanded'
  = render 'companies/menu'

.row
  -# if candidate_signed_in?
    .card#rate_company
      = render 'companies/show/rate'

  - if company.description.present?
    .card#company_description
      .row
        .columns.medium-4.medium-push-8
          = render 'companies/show/contact_data'
        .columns.medium-8.medium-pull-4
          .card-section.company__description
            != markdown company.description
  - else
    = blank_slate t('companies.show.no_description')

- if false
  .large-4.columns
    - if can? :edit, company
      .hide-for-small-only
        = link_to t('offers.add_new_offer'), new_offer_path, class: 'button expanded large'

app/views/companies/vote.js.haml
:plain
  document.getElementById('company_rating').innerHTML = '#{j t '.success'}<br/>#{j t '.avg_rating', rating: @rating, ratings: @ratings_count}';