config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  namespace :admin do
    resources :orders do
      member do
        patch :mark_paid
      end
    end
    resources :avatars do
      member do
        get :crop
      end
    end
  end

  ActiveAdmin.routes(self)
  get '/jobs/abroad', to: 'offers#abroad'
  get '/jobs/poland', to: 'offers#poland'
  get '/jobs/outdated_offer', to: 'offers#no_offer_found'
  get '/premium', to: 'products#index'
  get '/subscribe', to: 'newsletter_subscriptions#new', as: :new_newsletter_subscription
  resource :newsletter_subscription, only: %i[create destroy], path: '/subscribe'
  get '/unsubscribe', to: 'newsletter_subscriptions#unsubscribe'
  get '/regulamin', to: 'pages#tos'
  get '/regulamin/zalacznik1', to: 'pages#appendix1'
  get '/rodo', to: 'pages#rodo'
  get '/contact', to: 'pages#contact'
  get '/platnosci', to: 'pages#dotpay_payments', as: :payments

  resources :offers, path: '/jobs', except: :index do
    member do
      patch :publish
      patch :unpublish
      get :promote
      patch :promote, to: 'offers#add_premium'
    end

    collection do
      patch :batch_action
    end
    resources :applications, only: :create
  end
  post '/jobs/favourite/:offer_id', to: 'offer_saves#create', as: :offer_save
  post '/jobs/send_emai/:offer_id', to: 'offer_saves#email', as: :offer_email
  delete '/unfavourite_offer', to: 'offer_saves#destroy', as: :destroy_offer_save

  resource :cart, only: %i[show destroy], controller: 'cart' do
    patch :finalize
  end
  resources :cart_items, only: %i[create edit update destroy]

  get '/orders/place', to: 'orders#place', as: :place_order

  resources :orders, only: %i[index create show destroy] do
    get :payment
    get :thank_you
  end

  get '/offers/:offer_id/apply', to: 'applications#new', as: :new_offer_application
  get '/my_offers', to: 'offers#my_offers'

  resources :resumes
  get 'candidate/edit_skills', to: 'candidates#edit_skills'
  get 'candidate/edit_profile', to: 'candidates#edit', as: :edit_candidate_profile
  resource :profile, only: :show
  resource :dashboard, only: :show
  resources :education_items, except: %i[new edit]
  resources :work_items, except: %i[new edit]

  get '/imported_offers/select_company' => 'imported_offers#select_company'
  post '/imported_offers/publish' => 'imported_offers#publish'

  scope '/api' do
    get 'skills/(:term)' => 'autocomplete#skills', as: :autocomplete_skills
    get 'professions/(:term)' => 'autocomplete#professions', as: :autocomplete_professions
    get 'schools/(:term)' => 'autocomplete#schools', as: :autocomplete_schools
    get 'organizations/(:term)' => 'autocomplete#organizations', as: :autocomplete_organizations
    get 'provinces/(:country_id)/(:element_id)' => 'provinces#index', as: :provinces
    scope '/dotpay' do
      post 'confirm_payment' => 'dotpay#confirm'
    end
    scope '/jooble' do
      get 'jobs_feed.xml', to: 'feed#jooble'
    end
    scope '/jobsora' do
      get 'jobs_feed.xml', to: 'feed#jooble'
    end
    scope '/adzuna' do
      get 'jobs_feed.xml', to: 'feed#adzuna'
    end
    scope '/trovit' do
      get 'trovit_feed.xml', to: 'feed#trovit'
    end
    post '/confirm_lfw', to: 'candidates#confirm_lfw'
    scope '/hrlink' do
      get 'import', to: 'import#hrlink'
      get 'region_list', to: 'feed#region_list'
    end
  end

  devise_scope :candidate do
    get '/sign_up', to: 'candidates/registrations#new'
  end

  devise_for :candidates, controllers: {
    omniauth_callbacks: 'candidates/omniauth_callbacks',
    registrations: 'candidates/registrations', sessions: 'sessions'
  }
  devise_for :companies, controllers: { registrations: 'companies/registrations', sessions: 'sessions' }
  devise_for :users, controllers: { sessions: 'sessions' }, skip: :registrations, path: ''
  resources :candidates do
    get :mailing_list, on: :collection
    resources :favourite_offers, only: [:index]
  end
  get 'favourite_offer/(:candidate_id)/(:offer_id)', to: 'favourite_offers#create', as: 'add_offer_to_favourites'

  resources :companies, only: %i[show index update edit] do
    get :mailing_list, on: :collection
    resources :offers, only: [:index], controller: 'company_offers'
    resources :blog_posts, only: %i[show index create new], path: '/blog'
    member do
      post :vote
    end
  end
  resources :blog_posts, path: '/blog', only: %i[show destroy edit update]
  resources :skill_items, path: 'skills', only: %i[create destroy]
  resources :cv_items, path: 'cv_items', only: %i[create destroy]
  get '/edit_avatar', to: 'avatars#new'
  get '/crop_avatar', to: 'avatars#crop'
  resource :avatar, only: %i[create update]
  root to: 'home#home'
  get '*path', to: 'application#error404'
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_one :order, dependent: :destroy
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  scope :unfinalized, -> { where('NOT finalized') }

  def add_item(product, quantity = 1, offer_ids = nil)
    offer_ids = offer_ids.join(',') unless offer_ids.nil?
    product = Product.find_by(id: product.to_i) unless product.is_a?(Product)
    return false if !product || quantity.to_i < 1
    if (item = cart_items.find_by(product_id: product))
      item.update(quantity: item.quantity + quantity.to_i)
    else
      cart_items.create(product: product, quantity: quantity, offer_ids: offer_ids)
    end
  end

  def finalize!
    raise if finalized?
    update!(finalized_at: Time.now, finalized: true)
  end

  def readonly?
    saved_change_to_attribute?(:finalized) && finalized?
  end

  def empty?
    cart_items.empty?
  end

  def total(currency: 'pln', net: false)
    amount = cart_items.joins(:product).sum("cart_items.quantity * products.price_#{currency}")
    amount = Prices.net_price(amount) if net
    amount
  end

  def to_h
    cart_items.reduce({}) do |acc, item|
      acc.merge(item.product_id.to_s => item.quantity.to_s)
    end
  end

  def total_to_s(net: false, currency: nil)
    if currency
      Prices.formatted_price(total(currency: currency, net: net), currency)
    else
      Prices.formatted_prices(total(currency: :pln), total(currency: :eur), net: net)
    end
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  def show
    @cart = current_cart
    @cart_items = @cart.cart_items
  end

  def destroy
    current_cart.destroy
    redirect_to cart_path
  end

  def finalize
    currency = params[:currency].present? ? params[:currency] : nil
    order = current_cart.finalize!(currency)
    redirect_to order_payment_path(order)
  end
end

app/views/carts/_cart.html.haml
- if defined?(view_format) && view_format == :order
  .cart__table
    - if cart.cart_items.present?
      - currency = nil unless defined?(currency)
      %table
        %thead
          %tr
            %td= t('.quantity')
            %td= t('.product_name')
            %td= t('.unit_price')
            %td= t('.net_subtotal')
            %td= t('.gross')
        %tbody
          - cart.cart_items.each do |item|
            %tr
              %td!= item.quantity.to_s + " &times;".html_safe
              %td= item.product.local_name
              %td= item.unit_price_to_s(currency: currency)
              %td= item.subtotal_to_s(net: true, currency: currency)
              %td= item.subtotal_to_s(currency: currency)
          %tr.cart__total
            %td
            %td{colspan: 2}= t('.total')

            %td
              = cart.total_to_s(net: true, currency: currency)
            %td
              = cart.total_to_s(currency: currency)
            = render 'carts/discount_rows', cart: cart

- else
  - colspan = cart.readonly? ? 2 : 3
  .cart__table#cart
    %table.hover
      %thead
        %tr
          - unless cart.readonly?
            %td.cart_item__actions
          %td.cart_item__product_name= t('.product_name')
          %td.cart_item__unit_price= t('.unit_price')
          %td.cart_item__quantity= t('.quantity')
          %td.cart_item__subtotal= t('.subtotal')

      %tbody
        = render cart.cart_items
        %tr.cart__total
          -# Emoji 鬼 ogra U+1f479
          %td{colspan: colspan}
          %td 👹 #{t('.total')}
          %td= cart.total_to_s
          = render 'carts/discount_rows', cart: cart
    - if company_signed_in? && current_company.balance != 0
      .cart__discount__disclaimer
        %small= t('.discount_disclaimer')

    .text-right
      - unless cart.empty?
        = link_to fa_icon('trash-o', text: t('.empty_cart')), cart_path, method: :delete, class: 'button secondary'
      = link_to fa_icon('credit-card-alt', text: t('.place')), place_order_path, class: "button primary large #{cart.empty? ? 'disabled' : ''}"

app/views/carts/_discount_rows.html.haml
- colspan = cart.readonly? ? 2 : 3
- if cart.user.balance.to_f != 0 || (defined?(@order) && @order.deduction)
  :ruby
    deduction = if defined?(@order) && @order.persisted?
                 @order.deduction
               else
                 Prices.discount(cart.total, cart.user.balance)
               end
  - if deduction
    %tr.cart__discount
      %td{colspan: colspan}
      %td= t('carts.cart.discount')
      %td= Prices.formatted_price(deduction, 'pln')
  %tr.cart__amount_due
    %td{colspan: colspan}
    %td= t('carts.cart.amount_due')
    - if defined?(@order) && @order.persisted?
      %td= Prices.formatted_price(@order.amount_due, 'pln')
    - else
      %td= Prices.formatted_discounted_price(cart.total, cart.user.balance)